### ISSUE TITLE
Crashes while attempting to extract

### ISSUE THREAD

**Issue by whitequark** [Vector35/blob_extractor#2]
Backtrace:

```
[Default] extracting binaries from '/home/whitequark/Applications/qFlipper-x86_64-1.3.2.AppImage'...
[ScriptingProvider] Exception in thread Thread-2:
[ScriptingProvider] Traceback (most recent call last):
[ScriptingProvider]   File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
[ScriptingProvider]     self.run()
[ScriptingProvider]   File "/home/whitequark/Applications/binaryninja/plugins/../python/binaryninja/plugin.py", line 1056, in run
[ScriptingProvider]     self.task.run()
[ScriptingProvider]   File "/home/whitequark/.binaryninja/repositories/official/plugins/Vector35_blobextractor/tasks.py", line 196, in run
[ScriptingProvider]     files = _extract_from_file(self.filepath, extract_dir, scan_only=True)
[ScriptingProvider]             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ScriptingProvider]   File "/home/whitequark/.binaryninja/repositories/official/plugins/Vector35_blobextractor/tasks.py", line 63, in _extract_from_file
[ScriptingProvider]     config = ExtractionConfig(
[ScriptingProvider]              ^^^^^^^^^^^^^^^^^
[ScriptingProvider] TypeError: ExtractionConfig.__init__() got an unexpected keyword argument 'entropy_depth'
```

This is with the following Python packages freshly installed:

```
Package         Version
--------------- --------
appdirs         1.4.4
arpy            2.3.0
attrs           24.2.0
cffi            1.17.1
click           8.1.7
cryptography    43.0.3
cstruct         5.3
dissect.cstruct 4.2
fs              2.4.16
jefferson       0.4.5
lark            1.2.2
lief            0.15.1
lz4             4.3.3
lzallright      0.2.4
markdown-it-py  3.0.0
mdurl           0.1.2
pip             24.3.1
plotext         5.3.2
pluggy          1.5.0
pycparser       2.22
pyfatfs         1.1.0
Pygments        2.18.0
pyperscan       0.3.0
python-magic    0.4.27
rarfile         4.2
rich            13.9.4
setuptools      75.5.0
six             1.16.0
structlog       24.4.0
treelib         1.7.0
ubi-reader      0.8.9
unblob          24.11.13
unblob-native   0.1.5
```

**Comment by whitequark** [comment]
Downgrading to `unblob-24.9.30` solves the issue.

**Comment by zznop** [comment]
Fixed in this commit: https://github.com/Vector35/blob_extractor/commit/cfed8a817b8f221b55cdd81121361d5528d2c805 (and cut a 1.0.3 release).

If you installed the plugin from GitHub, you should be safe to `git pull` and then upgrade `unblob` back to `24.11.13`. I've included a `requirements.txt` to pin the Unblob package version to `24.11.13`. If you installed from the plugin manager, the new version should be approved shortly. Once you upgrade the plugin, it will hopefully upgrade unblob to the version in the requirements.txt.

As always, thanks for reporting this @whitequark! Let me know if you have any other issues.

**Comment by qkaiser** [comment]
Apologies for this. We do our best not to release API breaking changes but this one had to be done. We'll send notifications in the future now that we know this plugin exists :)

**Comment by zznop** [comment]
@qkaiser no problem, easy fix =)

I appreciate you keeping an eye out for us in the future.
